# local settings
# #
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # https://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: ajakcus_development

#   
# test:
#   <<: *default
#   database: ajakcus_test


# production:
#   <<: *default
#   database: ajakcus_production
#   username: ajakcus
#   password: <%= ENV['AJAKCUS_DATABASE_PASSWORD'] %>


# docker settings
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: ajakcus_development


test:
  <<: *default
  database: ajakcus_test